[target.'cfg(target_os = "linux")']
# Export `roc_*` symbols in linux executable. This is used for glue.
# On MacOS, these seem to be exported by default.
# Windows still needs to be tested.
rustflags = ["-Clink-args=-Wl,--export-dynamic-symbol,roc_*"]
